stages:
    - build
    - test
    - deploy

job1:
    stage: build
    script:
        - sleep 10
        - echo "Hello I am job 1"

job2:
    stage: build
    script:
        - sleep 20
        - echo "Hello I am job 2"

job3:
    stage: test
    script:
        - sleep 5
        - echo "Hello I am job 3"

job4:
    stage: deploy
    script:
        - sleep 10
        - echo "Hello I am job 4"
